### ISSUE TITLE
$expand always return 1 entity

### ISSUE THREAD

**Issue by fsundjaja** [mauriciolauffer/openui5-smart-mockserver#1]
I notice the $expand always returns 1 entity even the relationship is 1:M.

Any idea (1) if this is by design or limitation of this mockserver (2) how to make it work?

**Comment by mauriciolauffer** [comment]
It's a limitation in the mockserver itself.

You can check where the limit is applied here: https://github.com/SAP/openui5/blob/87fea0538822fd95bc4e0ae0bbb2a3c665da7c63/src/sap.ui.core/src/sap/ui/core/util/MockServer.js#L1822

You can create the entries and add to the mockserver manually, something like:
sap.ui.core.util.MockServer.getAll()[0].getEntitySetData('yourEntitySet').push( { YOUR NEW ENTRY HERE } )
